# Generated by Django 2.2.9 on 2020-01-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="title",),
        migrations.AddField(
            model_name="customtext",
            name="test",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
