# Generated by Django 2.2.9 on 2020-01-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200115_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='testdata',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
