# Generated by Django 2.2.9 on 2020-01-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_testdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='test1',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
